
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  ActionsMenu: typeof import("../../app/components/ActionsMenu.vue")['default']
  ConfirmDialog: typeof import("../../app/components/ConfirmDialog.vue")['default']
  ExportMenu: typeof import("../../app/components/ExportMenu.vue")['default']
  Skeleton: typeof import("../../app/components/Skeleton.vue")['default']
  SkeletonStatCard: typeof import("../../app/components/SkeletonStatCard.vue")['default']
  SkeletonTable: typeof import("../../app/components/SkeletonTable.vue")['default']
  AppHeader: typeof import("../../app/components/layout/AppHeader.vue")['default']
  AppSidebar: typeof import("../../app/components/layout/AppSidebar.vue")['default']
  NotificationDropdown: typeof import("../../app/components/layout/NotificationDropdown.vue")['default']
  ThemeToggle: typeof import("../../app/components/layout/ThemeToggle.vue")['default']
  Logo: typeof import("../../app/components/ui/Logo.vue")['default']
  ActivityLogFilters: typeof import("../../app/features/activity-logs/components/ActivityLogFilters.vue")['default']
  ActivityLogTable: typeof import("../../app/features/activity-logs/components/ActivityLogTable.vue")['default']
  ActivityLogTabs: typeof import("../../app/features/activity-logs/components/ActivityLogTabs.vue")['default']
  ActivityLogService: typeof import("../../app/features/activity-logs/services/activity-log.service")['default']
  Type: typeof import("../../app/features/activity-logs/type")['default']
  AccountDisabledNotice: typeof import("../../app/features/auth/components/AccountDisabledNotice.vue")['default']
  CreateCompanyForm: typeof import("../../app/features/auth/components/CreateCompanyForm.vue")['default']
  CreateSuperAdminForm: typeof import("../../app/features/auth/components/CreateSuperAdminForm.vue")['default']
  EditProfileModal: typeof import("../../app/features/auth/components/EditProfileModal.vue")['default']
  ForgotPasswordForm: typeof import("../../app/features/auth/components/ForgotPasswordForm.vue")['default']
  LoginForm: typeof import("../../app/features/auth/components/LoginForm.vue")['default']
  ReservationSettingsForm: typeof import("../../app/features/auth/components/ReservationSettingsForm.vue")['default']
  ResetPasswordForm: typeof import("../../app/features/auth/components/ResetPasswordForm.vue")['default']
  SetPasswordForm: typeof import("../../app/features/auth/components/SetPasswordForm.vue")['default']
  AuthService: typeof import("../../app/features/auth/services/auth.service")['default']
  AvailabilityGrid: typeof import("../../app/features/availability/components/AvailabilityGrid.vue")['default']
  AvailabilityHeader: typeof import("../../app/features/availability/components/AvailabilityHeader.vue")['default']
  AvailabilityLegend: typeof import("../../app/features/availability/components/AvailabilityLegend.vue")['default']
  AvailabilityNav: typeof import("../../app/features/availability/components/AvailabilityNav.vue")['default']
  AvailabilitySearch: typeof import("../../app/features/availability/components/AvailabilitySearch.vue")['default']
  AvailabilityStats: typeof import("../../app/features/availability/components/AvailabilityStats.vue")['default']
  EquipmentAvailabilityGrid: typeof import("../../app/features/availability/components/EquipmentAvailabilityGrid.vue")['default']
  ScheduleGrid: typeof import("../../app/features/availability/components/ScheduleGrid.vue")['default']
  WeekDayStrip: typeof import("../../app/features/availability/components/WeekDayStrip.vue")['default']
  ScheduleBuffer: typeof import("../../app/features/availability/scheduleBuffer")['default']
  Types: typeof import("../../app/features/availability/types")['default']
  CalendarWidget: typeof import("../../app/features/dashboard/components/CalendarWidget.vue")['default']
  DashboardHeader: typeof import("../../app/features/dashboard/components/DashboardHeader.vue")['default']
  DashboardReservationStatusBadge: typeof import("../../app/features/dashboard/components/DashboardReservationStatusBadge.vue")['default']
  MiniCalendar: typeof import("../../app/features/dashboard/components/MiniCalendar.vue")['default']
  RecentActivity: typeof import("../../app/features/dashboard/components/RecentActivity.vue")['default']
  RoomOccupancy: typeof import("../../app/features/dashboard/components/RoomOccupancy.vue")['default']
  StatCard: typeof import("../../app/features/dashboard/components/StatCard.vue")['default']
  StatsGrid: typeof import("../../app/features/dashboard/components/StatsGrid.vue")['default']
  TodoWidget: typeof import("../../app/features/dashboard/components/TodoWidget.vue")['default']
  UpcomingReservations: typeof import("../../app/features/dashboard/components/UpcomingReservations.vue")['default']
  DashboardService: typeof import("../../app/features/dashboard/services/dashboard.service")['default']
  CategoryDetailsModal: typeof import("../../app/features/equipment-categories/components/CategoryDetailsModal.vue")['default']
  CreateEquipmentCategoryModal: typeof import("../../app/features/equipment-categories/components/CreateEquipmentCategoryModal.vue")['default']
  EquipmentCategoriesHeader: typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesHeader.vue")['default']
  EquipmentCategoriesSearch: typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesSearch.vue")['default']
  EquipmentCategoriesStats: typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesStats.vue")['default']
  EquipmentCategoriesTable: typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesTable.vue")['default']
  EquipmentCategoryService: typeof import("../../app/features/equipment-categories/services/equipment-category.service")['default']
  CreateEquipmentModal: typeof import("../../app/features/equipments/components/CreateEquipmentModal.vue")['default']
  EquipmentStateBadge: typeof import("../../app/features/equipments/components/EquipmentStateBadge.vue")['default']
  EquipmentsFilters: typeof import("../../app/features/equipments/components/EquipmentsFilters.vue")['default']
  EquipmentsHeader: typeof import("../../app/features/equipments/components/EquipmentsHeader.vue")['default']
  EquipmentsStats: typeof import("../../app/features/equipments/components/EquipmentsStats.vue")['default']
  EquipmentsTable: typeof import("../../app/features/equipments/components/EquipmentsTable.vue")['default']
  UpdateEquipmentStatusModal: typeof import("../../app/features/equipments/components/UpdateEquipmentStatusModal.vue")['default']
  UsageTypeBadge: typeof import("../../app/features/equipments/components/UsageTypeBadge.vue")['default']
  EquipmentService: typeof import("../../app/features/equipments/services/equipment.service")['default']
  MarketingCallToAction: typeof import("../../app/features/marketing/components/MarketingCallToAction.vue")['default']
  MarketingDashboardPreview: typeof import("../../app/features/marketing/components/MarketingDashboardPreview.vue")['default']
  MarketingFeatureCard: typeof import("../../app/features/marketing/components/MarketingFeatureCard.vue")['default']
  MarketingFeaturesGrid: typeof import("../../app/features/marketing/components/MarketingFeaturesGrid.vue")['default']
  MarketingFooter: typeof import("../../app/features/marketing/components/MarketingFooter.vue")['default']
  MarketingHeroSection: typeof import("../../app/features/marketing/components/MarketingHeroSection.vue")['default']
  MarketingNavbar: typeof import("../../app/features/marketing/components/MarketingNavbar.vue")['default']
  MarketingOnboardingStep: typeof import("../../app/features/marketing/components/MarketingOnboardingStep.vue")['default']
  MarketingOnboardingSteps: typeof import("../../app/features/marketing/components/MarketingOnboardingSteps.vue")['default']
  NotificationService: typeof import("../../app/features/notifications/services/notification.service")['default']
  CompanyService: typeof import("../../app/features/onboarding/services/company.service")['default']
  CreateReservationModal: typeof import("../../app/features/reservations/components/CreateReservationModal.vue")['default']
  DailySummary: typeof import("../../app/features/reservations/components/DailySummary.vue")['default']
  ReservationDetailsModal: typeof import("../../app/features/reservations/components/ReservationDetailsModal.vue")['default']
  ReservationStatusBadge: typeof import("../../app/features/reservations/components/ReservationStatusBadge.vue")['default']
  ReservationsFilters: typeof import("../../app/features/reservations/components/ReservationsFilters.vue")['default']
  ReservationsHeader: typeof import("../../app/features/reservations/components/ReservationsHeader.vue")['default']
  ReservationsTable: typeof import("../../app/features/reservations/components/ReservationsTable.vue")['default']
  SelectEquipmentPanel: typeof import("../../app/features/reservations/components/SelectEquipmentPanel.vue")['default']
  WeekStrip: typeof import("../../app/features/reservations/components/WeekStrip.vue")['default']
  ReservationsService: typeof import("../../app/features/reservations/services/reservations.service")['default']
  CreateRoomModal: typeof import("../../app/features/rooms/components/CreateRoomModal.vue")['default']
  RoomStatusBadge: typeof import("../../app/features/rooms/components/RoomStatusBadge.vue")['default']
  RoomTypeBadge: typeof import("../../app/features/rooms/components/RoomTypeBadge.vue")['default']
  RoomsFilters: typeof import("../../app/features/rooms/components/RoomsFilters.vue")['default']
  RoomsHeader: typeof import("../../app/features/rooms/components/RoomsHeader.vue")['default']
  RoomsStats: typeof import("../../app/features/rooms/components/RoomsStats.vue")['default']
  RoomsTable: typeof import("../../app/features/rooms/components/RoomsTable.vue")['default']
  RoomService: typeof import("../../app/features/rooms/services/room.service")['default']
  AboutCard: typeof import("../../app/features/settings/components/AboutCard.vue")['default']
  BusinessHoursCard: typeof import("../../app/features/settings/components/BusinessHoursCard.vue")['default']
  ChangePasswordModal: typeof import("../../app/features/settings/components/ChangePasswordModal.vue")['default']
  CompanyInfoCard: typeof import("../../app/features/settings/components/CompanyInfoCard.vue")['default']
  EditBusinessHoursModal: typeof import("../../app/features/settings/components/EditBusinessHoursModal.vue")['default']
  EditCompanyInfoModal: typeof import("../../app/features/settings/components/EditCompanyInfoModal.vue")['default']
  NotificationsCard: typeof import("../../app/features/settings/components/NotificationsCard.vue")['default']
  PasswordCard: typeof import("../../app/features/settings/components/PasswordCard.vue")['default']
  EntrepriseService: typeof import("../../app/features/settings/services/entreprise.service")['default']
  NotificationPreferenceService: typeof import("../../app/features/settings/services/notification-preference.service")['default']
  ReservationSettingService: typeof import("../../app/features/settings/services/reservation-setting.service")['default']
  CloseTicketModal: typeof import("../../app/features/tickets/components/CloseTicketModal.vue")['default']
  CreateTicketModal: typeof import("../../app/features/tickets/components/CreateTicketModal.vue")['default']
  RecentTicketsWidget: typeof import("../../app/features/tickets/components/RecentTicketsWidget.vue")['default']
  TicketStatsCards: typeof import("../../app/features/tickets/components/TicketStatsCards.vue")['default']
  TicketStatusBadge: typeof import("../../app/features/tickets/components/TicketStatusBadge.vue")['default']
  TicketsTable: typeof import("../../app/features/tickets/components/TicketsTable.vue")['default']
  TicketService: typeof import("../../app/features/tickets/services/ticket.service")['default']
  CreateUserModal: typeof import("../../app/features/users/components/CreateUserModal.vue")['default']
  RoleBadge: typeof import("../../app/features/users/components/RoleBadge.vue")['default']
  UserStatusBadge: typeof import("../../app/features/users/components/UserStatusBadge.vue")['default']
  UsersFilters: typeof import("../../app/features/users/components/UsersFilters.vue")['default']
  UsersHeader: typeof import("../../app/features/users/components/UsersHeader.vue")['default']
  UsersStats: typeof import("../../app/features/users/components/UsersStats.vue")['default']
  UsersTable: typeof import("../../app/features/users/components/UsersTable.vue")['default']
  UserService: typeof import("../../app/features/users/services/user.service")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyActionsMenu: LazyComponent<typeof import("../../app/components/ActionsMenu.vue")['default']>
  LazyConfirmDialog: LazyComponent<typeof import("../../app/components/ConfirmDialog.vue")['default']>
  LazyExportMenu: LazyComponent<typeof import("../../app/components/ExportMenu.vue")['default']>
  LazySkeleton: LazyComponent<typeof import("../../app/components/Skeleton.vue")['default']>
  LazySkeletonStatCard: LazyComponent<typeof import("../../app/components/SkeletonStatCard.vue")['default']>
  LazySkeletonTable: LazyComponent<typeof import("../../app/components/SkeletonTable.vue")['default']>
  LazyAppHeader: LazyComponent<typeof import("../../app/components/layout/AppHeader.vue")['default']>
  LazyAppSidebar: LazyComponent<typeof import("../../app/components/layout/AppSidebar.vue")['default']>
  LazyNotificationDropdown: LazyComponent<typeof import("../../app/components/layout/NotificationDropdown.vue")['default']>
  LazyThemeToggle: LazyComponent<typeof import("../../app/components/layout/ThemeToggle.vue")['default']>
  LazyLogo: LazyComponent<typeof import("../../app/components/ui/Logo.vue")['default']>
  LazyActivityLogFilters: LazyComponent<typeof import("../../app/features/activity-logs/components/ActivityLogFilters.vue")['default']>
  LazyActivityLogTable: LazyComponent<typeof import("../../app/features/activity-logs/components/ActivityLogTable.vue")['default']>
  LazyActivityLogTabs: LazyComponent<typeof import("../../app/features/activity-logs/components/ActivityLogTabs.vue")['default']>
  LazyActivityLogService: LazyComponent<typeof import("../../app/features/activity-logs/services/activity-log.service")['default']>
  LazyType: LazyComponent<typeof import("../../app/features/activity-logs/type")['default']>
  LazyAccountDisabledNotice: LazyComponent<typeof import("../../app/features/auth/components/AccountDisabledNotice.vue")['default']>
  LazyCreateCompanyForm: LazyComponent<typeof import("../../app/features/auth/components/CreateCompanyForm.vue")['default']>
  LazyCreateSuperAdminForm: LazyComponent<typeof import("../../app/features/auth/components/CreateSuperAdminForm.vue")['default']>
  LazyEditProfileModal: LazyComponent<typeof import("../../app/features/auth/components/EditProfileModal.vue")['default']>
  LazyForgotPasswordForm: LazyComponent<typeof import("../../app/features/auth/components/ForgotPasswordForm.vue")['default']>
  LazyLoginForm: LazyComponent<typeof import("../../app/features/auth/components/LoginForm.vue")['default']>
  LazyReservationSettingsForm: LazyComponent<typeof import("../../app/features/auth/components/ReservationSettingsForm.vue")['default']>
  LazyResetPasswordForm: LazyComponent<typeof import("../../app/features/auth/components/ResetPasswordForm.vue")['default']>
  LazySetPasswordForm: LazyComponent<typeof import("../../app/features/auth/components/SetPasswordForm.vue")['default']>
  LazyAuthService: LazyComponent<typeof import("../../app/features/auth/services/auth.service")['default']>
  LazyAvailabilityGrid: LazyComponent<typeof import("../../app/features/availability/components/AvailabilityGrid.vue")['default']>
  LazyAvailabilityHeader: LazyComponent<typeof import("../../app/features/availability/components/AvailabilityHeader.vue")['default']>
  LazyAvailabilityLegend: LazyComponent<typeof import("../../app/features/availability/components/AvailabilityLegend.vue")['default']>
  LazyAvailabilityNav: LazyComponent<typeof import("../../app/features/availability/components/AvailabilityNav.vue")['default']>
  LazyAvailabilitySearch: LazyComponent<typeof import("../../app/features/availability/components/AvailabilitySearch.vue")['default']>
  LazyAvailabilityStats: LazyComponent<typeof import("../../app/features/availability/components/AvailabilityStats.vue")['default']>
  LazyEquipmentAvailabilityGrid: LazyComponent<typeof import("../../app/features/availability/components/EquipmentAvailabilityGrid.vue")['default']>
  LazyScheduleGrid: LazyComponent<typeof import("../../app/features/availability/components/ScheduleGrid.vue")['default']>
  LazyWeekDayStrip: LazyComponent<typeof import("../../app/features/availability/components/WeekDayStrip.vue")['default']>
  LazyScheduleBuffer: LazyComponent<typeof import("../../app/features/availability/scheduleBuffer")['default']>
  LazyTypes: LazyComponent<typeof import("../../app/features/availability/types")['default']>
  LazyCalendarWidget: LazyComponent<typeof import("../../app/features/dashboard/components/CalendarWidget.vue")['default']>
  LazyDashboardHeader: LazyComponent<typeof import("../../app/features/dashboard/components/DashboardHeader.vue")['default']>
  LazyDashboardReservationStatusBadge: LazyComponent<typeof import("../../app/features/dashboard/components/DashboardReservationStatusBadge.vue")['default']>
  LazyMiniCalendar: LazyComponent<typeof import("../../app/features/dashboard/components/MiniCalendar.vue")['default']>
  LazyRecentActivity: LazyComponent<typeof import("../../app/features/dashboard/components/RecentActivity.vue")['default']>
  LazyRoomOccupancy: LazyComponent<typeof import("../../app/features/dashboard/components/RoomOccupancy.vue")['default']>
  LazyStatCard: LazyComponent<typeof import("../../app/features/dashboard/components/StatCard.vue")['default']>
  LazyStatsGrid: LazyComponent<typeof import("../../app/features/dashboard/components/StatsGrid.vue")['default']>
  LazyTodoWidget: LazyComponent<typeof import("../../app/features/dashboard/components/TodoWidget.vue")['default']>
  LazyUpcomingReservations: LazyComponent<typeof import("../../app/features/dashboard/components/UpcomingReservations.vue")['default']>
  LazyDashboardService: LazyComponent<typeof import("../../app/features/dashboard/services/dashboard.service")['default']>
  LazyCategoryDetailsModal: LazyComponent<typeof import("../../app/features/equipment-categories/components/CategoryDetailsModal.vue")['default']>
  LazyCreateEquipmentCategoryModal: LazyComponent<typeof import("../../app/features/equipment-categories/components/CreateEquipmentCategoryModal.vue")['default']>
  LazyEquipmentCategoriesHeader: LazyComponent<typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesHeader.vue")['default']>
  LazyEquipmentCategoriesSearch: LazyComponent<typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesSearch.vue")['default']>
  LazyEquipmentCategoriesStats: LazyComponent<typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesStats.vue")['default']>
  LazyEquipmentCategoriesTable: LazyComponent<typeof import("../../app/features/equipment-categories/components/EquipmentCategoriesTable.vue")['default']>
  LazyEquipmentCategoryService: LazyComponent<typeof import("../../app/features/equipment-categories/services/equipment-category.service")['default']>
  LazyCreateEquipmentModal: LazyComponent<typeof import("../../app/features/equipments/components/CreateEquipmentModal.vue")['default']>
  LazyEquipmentStateBadge: LazyComponent<typeof import("../../app/features/equipments/components/EquipmentStateBadge.vue")['default']>
  LazyEquipmentsFilters: LazyComponent<typeof import("../../app/features/equipments/components/EquipmentsFilters.vue")['default']>
  LazyEquipmentsHeader: LazyComponent<typeof import("../../app/features/equipments/components/EquipmentsHeader.vue")['default']>
  LazyEquipmentsStats: LazyComponent<typeof import("../../app/features/equipments/components/EquipmentsStats.vue")['default']>
  LazyEquipmentsTable: LazyComponent<typeof import("../../app/features/equipments/components/EquipmentsTable.vue")['default']>
  LazyUpdateEquipmentStatusModal: LazyComponent<typeof import("../../app/features/equipments/components/UpdateEquipmentStatusModal.vue")['default']>
  LazyUsageTypeBadge: LazyComponent<typeof import("../../app/features/equipments/components/UsageTypeBadge.vue")['default']>
  LazyEquipmentService: LazyComponent<typeof import("../../app/features/equipments/services/equipment.service")['default']>
  LazyMarketingCallToAction: LazyComponent<typeof import("../../app/features/marketing/components/MarketingCallToAction.vue")['default']>
  LazyMarketingDashboardPreview: LazyComponent<typeof import("../../app/features/marketing/components/MarketingDashboardPreview.vue")['default']>
  LazyMarketingFeatureCard: LazyComponent<typeof import("../../app/features/marketing/components/MarketingFeatureCard.vue")['default']>
  LazyMarketingFeaturesGrid: LazyComponent<typeof import("../../app/features/marketing/components/MarketingFeaturesGrid.vue")['default']>
  LazyMarketingFooter: LazyComponent<typeof import("../../app/features/marketing/components/MarketingFooter.vue")['default']>
  LazyMarketingHeroSection: LazyComponent<typeof import("../../app/features/marketing/components/MarketingHeroSection.vue")['default']>
  LazyMarketingNavbar: LazyComponent<typeof import("../../app/features/marketing/components/MarketingNavbar.vue")['default']>
  LazyMarketingOnboardingStep: LazyComponent<typeof import("../../app/features/marketing/components/MarketingOnboardingStep.vue")['default']>
  LazyMarketingOnboardingSteps: LazyComponent<typeof import("../../app/features/marketing/components/MarketingOnboardingSteps.vue")['default']>
  LazyNotificationService: LazyComponent<typeof import("../../app/features/notifications/services/notification.service")['default']>
  LazyCompanyService: LazyComponent<typeof import("../../app/features/onboarding/services/company.service")['default']>
  LazyCreateReservationModal: LazyComponent<typeof import("../../app/features/reservations/components/CreateReservationModal.vue")['default']>
  LazyDailySummary: LazyComponent<typeof import("../../app/features/reservations/components/DailySummary.vue")['default']>
  LazyReservationDetailsModal: LazyComponent<typeof import("../../app/features/reservations/components/ReservationDetailsModal.vue")['default']>
  LazyReservationStatusBadge: LazyComponent<typeof import("../../app/features/reservations/components/ReservationStatusBadge.vue")['default']>
  LazyReservationsFilters: LazyComponent<typeof import("../../app/features/reservations/components/ReservationsFilters.vue")['default']>
  LazyReservationsHeader: LazyComponent<typeof import("../../app/features/reservations/components/ReservationsHeader.vue")['default']>
  LazyReservationsTable: LazyComponent<typeof import("../../app/features/reservations/components/ReservationsTable.vue")['default']>
  LazySelectEquipmentPanel: LazyComponent<typeof import("../../app/features/reservations/components/SelectEquipmentPanel.vue")['default']>
  LazyWeekStrip: LazyComponent<typeof import("../../app/features/reservations/components/WeekStrip.vue")['default']>
  LazyReservationsService: LazyComponent<typeof import("../../app/features/reservations/services/reservations.service")['default']>
  LazyCreateRoomModal: LazyComponent<typeof import("../../app/features/rooms/components/CreateRoomModal.vue")['default']>
  LazyRoomStatusBadge: LazyComponent<typeof import("../../app/features/rooms/components/RoomStatusBadge.vue")['default']>
  LazyRoomTypeBadge: LazyComponent<typeof import("../../app/features/rooms/components/RoomTypeBadge.vue")['default']>
  LazyRoomsFilters: LazyComponent<typeof import("../../app/features/rooms/components/RoomsFilters.vue")['default']>
  LazyRoomsHeader: LazyComponent<typeof import("../../app/features/rooms/components/RoomsHeader.vue")['default']>
  LazyRoomsStats: LazyComponent<typeof import("../../app/features/rooms/components/RoomsStats.vue")['default']>
  LazyRoomsTable: LazyComponent<typeof import("../../app/features/rooms/components/RoomsTable.vue")['default']>
  LazyRoomService: LazyComponent<typeof import("../../app/features/rooms/services/room.service")['default']>
  LazyAboutCard: LazyComponent<typeof import("../../app/features/settings/components/AboutCard.vue")['default']>
  LazyBusinessHoursCard: LazyComponent<typeof import("../../app/features/settings/components/BusinessHoursCard.vue")['default']>
  LazyChangePasswordModal: LazyComponent<typeof import("../../app/features/settings/components/ChangePasswordModal.vue")['default']>
  LazyCompanyInfoCard: LazyComponent<typeof import("../../app/features/settings/components/CompanyInfoCard.vue")['default']>
  LazyEditBusinessHoursModal: LazyComponent<typeof import("../../app/features/settings/components/EditBusinessHoursModal.vue")['default']>
  LazyEditCompanyInfoModal: LazyComponent<typeof import("../../app/features/settings/components/EditCompanyInfoModal.vue")['default']>
  LazyNotificationsCard: LazyComponent<typeof import("../../app/features/settings/components/NotificationsCard.vue")['default']>
  LazyPasswordCard: LazyComponent<typeof import("../../app/features/settings/components/PasswordCard.vue")['default']>
  LazyEntrepriseService: LazyComponent<typeof import("../../app/features/settings/services/entreprise.service")['default']>
  LazyNotificationPreferenceService: LazyComponent<typeof import("../../app/features/settings/services/notification-preference.service")['default']>
  LazyReservationSettingService: LazyComponent<typeof import("../../app/features/settings/services/reservation-setting.service")['default']>
  LazyCloseTicketModal: LazyComponent<typeof import("../../app/features/tickets/components/CloseTicketModal.vue")['default']>
  LazyCreateTicketModal: LazyComponent<typeof import("../../app/features/tickets/components/CreateTicketModal.vue")['default']>
  LazyRecentTicketsWidget: LazyComponent<typeof import("../../app/features/tickets/components/RecentTicketsWidget.vue")['default']>
  LazyTicketStatsCards: LazyComponent<typeof import("../../app/features/tickets/components/TicketStatsCards.vue")['default']>
  LazyTicketStatusBadge: LazyComponent<typeof import("../../app/features/tickets/components/TicketStatusBadge.vue")['default']>
  LazyTicketsTable: LazyComponent<typeof import("../../app/features/tickets/components/TicketsTable.vue")['default']>
  LazyTicketService: LazyComponent<typeof import("../../app/features/tickets/services/ticket.service")['default']>
  LazyCreateUserModal: LazyComponent<typeof import("../../app/features/users/components/CreateUserModal.vue")['default']>
  LazyRoleBadge: LazyComponent<typeof import("../../app/features/users/components/RoleBadge.vue")['default']>
  LazyUserStatusBadge: LazyComponent<typeof import("../../app/features/users/components/UserStatusBadge.vue")['default']>
  LazyUsersFilters: LazyComponent<typeof import("../../app/features/users/components/UsersFilters.vue")['default']>
  LazyUsersHeader: LazyComponent<typeof import("../../app/features/users/components/UsersHeader.vue")['default']>
  LazyUsersStats: LazyComponent<typeof import("../../app/features/users/components/UsersStats.vue")['default']>
  LazyUsersTable: LazyComponent<typeof import("../../app/features/users/components/UsersTable.vue")['default']>
  LazyUserService: LazyComponent<typeof import("../../app/features/users/services/user.service")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
