// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05/08/2026 10:16:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/features/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/plugins/**/*.{js,ts,mjs}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/composables/**/*.{js,ts,mjs}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/utils/**/*.{js,ts,mjs}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/labar/Desktop/Stage/CompanyFlow/frontend-reservation/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;