
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const ActionsMenu: typeof import("../app/components/ActionsMenu.vue")['default']
export const ConfirmDialog: typeof import("../app/components/ConfirmDialog.vue")['default']
export const ExportMenu: typeof import("../app/components/ExportMenu.vue")['default']
export const Skeleton: typeof import("../app/components/Skeleton.vue")['default']
export const SkeletonStatCard: typeof import("../app/components/SkeletonStatCard.vue")['default']
export const SkeletonTable: typeof import("../app/components/SkeletonTable.vue")['default']
export const AppHeader: typeof import("../app/components/layout/AppHeader.vue")['default']
export const AppSidebar: typeof import("../app/components/layout/AppSidebar.vue")['default']
export const NotificationDropdown: typeof import("../app/components/layout/NotificationDropdown.vue")['default']
export const ThemeToggle: typeof import("../app/components/layout/ThemeToggle.vue")['default']
export const AppBootLoader: typeof import("../app/components/ui/AppBootLoader.vue")['default']
export const Logo: typeof import("../app/components/ui/Logo.vue")['default']
export const PageLoader: typeof import("../app/components/ui/PageLoader.vue")['default']
export const ToastContainer: typeof import("../app/components/ui/ToastContainer.vue")['default']
export const ActivityLogFilters: typeof import("../app/features/activity-logs/components/ActivityLogFilters.vue")['default']
export const ActivityLogTable: typeof import("../app/features/activity-logs/components/ActivityLogTable.vue")['default']
export const ActivityLogTabs: typeof import("../app/features/activity-logs/components/ActivityLogTabs.vue")['default']
export const ActivityLogService: typeof import("../app/features/activity-logs/services/activity-log.service")['default']
export const Type: typeof import("../app/features/activity-logs/type")['default']
export const AccountDisabledNotice: typeof import("../app/features/auth/components/AccountDisabledNotice.vue")['default']
export const CreateCompanyForm: typeof import("../app/features/auth/components/CreateCompanyForm.vue")['default']
export const CreateSuperAdminForm: typeof import("../app/features/auth/components/CreateSuperAdminForm.vue")['default']
export const EditProfileModal: typeof import("../app/features/auth/components/EditProfileModal.vue")['default']
export const ForgotPasswordForm: typeof import("../app/features/auth/components/ForgotPasswordForm.vue")['default']
export const LoginForm: typeof import("../app/features/auth/components/LoginForm.vue")['default']
export const ReservationSettingsForm: typeof import("../app/features/auth/components/ReservationSettingsForm.vue")['default']
export const ResetPasswordForm: typeof import("../app/features/auth/components/ResetPasswordForm.vue")['default']
export const SetPasswordForm: typeof import("../app/features/auth/components/SetPasswordForm.vue")['default']
export const AuthService: typeof import("../app/features/auth/services/auth.service")['default']
export const AvailabilityGrid: typeof import("../app/features/availability/components/AvailabilityGrid.vue")['default']
export const AvailabilityHeader: typeof import("../app/features/availability/components/AvailabilityHeader.vue")['default']
export const AvailabilityLegend: typeof import("../app/features/availability/components/AvailabilityLegend.vue")['default']
export const AvailabilityNav: typeof import("../app/features/availability/components/AvailabilityNav.vue")['default']
export const AvailabilitySearch: typeof import("../app/features/availability/components/AvailabilitySearch.vue")['default']
export const AvailabilityStats: typeof import("../app/features/availability/components/AvailabilityStats.vue")['default']
export const EquipmentAvailabilityGrid: typeof import("../app/features/availability/components/EquipmentAvailabilityGrid.vue")['default']
export const ScheduleGrid: typeof import("../app/features/availability/components/ScheduleGrid.vue")['default']
export const WeekDayStrip: typeof import("../app/features/availability/components/WeekDayStrip.vue")['default']
export const ScheduleBuffer: typeof import("../app/features/availability/scheduleBuffer")['default']
export const Types: typeof import("../app/features/availability/types")['default']
export const CalendarWidget: typeof import("../app/features/dashboard/components/CalendarWidget.vue")['default']
export const DashboardHeader: typeof import("../app/features/dashboard/components/DashboardHeader.vue")['default']
export const DashboardReservationStatusBadge: typeof import("../app/features/dashboard/components/DashboardReservationStatusBadge.vue")['default']
export const MiniCalendar: typeof import("../app/features/dashboard/components/MiniCalendar.vue")['default']
export const RecentActivity: typeof import("../app/features/dashboard/components/RecentActivity.vue")['default']
export const RoomOccupancy: typeof import("../app/features/dashboard/components/RoomOccupancy.vue")['default']
export const StatCard: typeof import("../app/features/dashboard/components/StatCard.vue")['default']
export const StatsGrid: typeof import("../app/features/dashboard/components/StatsGrid.vue")['default']
export const TodoWidget: typeof import("../app/features/dashboard/components/TodoWidget.vue")['default']
export const UpcomingReservations: typeof import("../app/features/dashboard/components/UpcomingReservations.vue")['default']
export const DashboardService: typeof import("../app/features/dashboard/services/dashboard.service")['default']
export const CategoryDetailsModal: typeof import("../app/features/equipment-categories/components/CategoryDetailsModal.vue")['default']
export const CreateEquipmentCategoryModal: typeof import("../app/features/equipment-categories/components/CreateEquipmentCategoryModal.vue")['default']
export const EquipmentCategoriesHeader: typeof import("../app/features/equipment-categories/components/EquipmentCategoriesHeader.vue")['default']
export const EquipmentCategoriesSearch: typeof import("../app/features/equipment-categories/components/EquipmentCategoriesSearch.vue")['default']
export const EquipmentCategoriesStats: typeof import("../app/features/equipment-categories/components/EquipmentCategoriesStats.vue")['default']
export const EquipmentCategoriesTable: typeof import("../app/features/equipment-categories/components/EquipmentCategoriesTable.vue")['default']
export const EquipmentCategoryService: typeof import("../app/features/equipment-categories/services/equipment-category.service")['default']
export const CreateEquipmentModal: typeof import("../app/features/equipments/components/CreateEquipmentModal.vue")['default']
export const EquipmentStateBadge: typeof import("../app/features/equipments/components/EquipmentStateBadge.vue")['default']
export const EquipmentsFilters: typeof import("../app/features/equipments/components/EquipmentsFilters.vue")['default']
export const EquipmentsHeader: typeof import("../app/features/equipments/components/EquipmentsHeader.vue")['default']
export const EquipmentsStats: typeof import("../app/features/equipments/components/EquipmentsStats.vue")['default']
export const EquipmentsTable: typeof import("../app/features/equipments/components/EquipmentsTable.vue")['default']
export const UpdateEquipmentStatusModal: typeof import("../app/features/equipments/components/UpdateEquipmentStatusModal.vue")['default']
export const UsageTypeBadge: typeof import("../app/features/equipments/components/UsageTypeBadge.vue")['default']
export const EquipmentService: typeof import("../app/features/equipments/services/equipment.service")['default']
export const MarketingCallToAction: typeof import("../app/features/marketing/components/MarketingCallToAction.vue")['default']
export const MarketingDashboardPreview: typeof import("../app/features/marketing/components/MarketingDashboardPreview.vue")['default']
export const MarketingFeatureCard: typeof import("../app/features/marketing/components/MarketingFeatureCard.vue")['default']
export const MarketingFeaturesGrid: typeof import("../app/features/marketing/components/MarketingFeaturesGrid.vue")['default']
export const MarketingFooter: typeof import("../app/features/marketing/components/MarketingFooter.vue")['default']
export const MarketingHeroSection: typeof import("../app/features/marketing/components/MarketingHeroSection.vue")['default']
export const MarketingNavbar: typeof import("../app/features/marketing/components/MarketingNavbar.vue")['default']
export const MarketingOnboardingStep: typeof import("../app/features/marketing/components/MarketingOnboardingStep.vue")['default']
export const MarketingOnboardingSteps: typeof import("../app/features/marketing/components/MarketingOnboardingSteps.vue")['default']
export const NotificationService: typeof import("../app/features/notifications/services/notification.service")['default']
export const CompanyService: typeof import("../app/features/onboarding/services/company.service")['default']
export const CreateReservationModal: typeof import("../app/features/reservations/components/CreateReservationModal.vue")['default']
export const DailySummary: typeof import("../app/features/reservations/components/DailySummary.vue")['default']
export const ReservationDetailsModal: typeof import("../app/features/reservations/components/ReservationDetailsModal.vue")['default']
export const ReservationStatusBadge: typeof import("../app/features/reservations/components/ReservationStatusBadge.vue")['default']
export const ReservationsFilters: typeof import("../app/features/reservations/components/ReservationsFilters.vue")['default']
export const ReservationsHeader: typeof import("../app/features/reservations/components/ReservationsHeader.vue")['default']
export const ReservationsTable: typeof import("../app/features/reservations/components/ReservationsTable.vue")['default']
export const SelectEquipmentPanel: typeof import("../app/features/reservations/components/SelectEquipmentPanel.vue")['default']
export const WeekStrip: typeof import("../app/features/reservations/components/WeekStrip.vue")['default']
export const ReservationsService: typeof import("../app/features/reservations/services/reservations.service")['default']
export const CreateRoomModal: typeof import("../app/features/rooms/components/CreateRoomModal.vue")['default']
export const RoomStatusBadge: typeof import("../app/features/rooms/components/RoomStatusBadge.vue")['default']
export const RoomTypeBadge: typeof import("../app/features/rooms/components/RoomTypeBadge.vue")['default']
export const RoomsFilters: typeof import("../app/features/rooms/components/RoomsFilters.vue")['default']
export const RoomsHeader: typeof import("../app/features/rooms/components/RoomsHeader.vue")['default']
export const RoomsStats: typeof import("../app/features/rooms/components/RoomsStats.vue")['default']
export const RoomsTable: typeof import("../app/features/rooms/components/RoomsTable.vue")['default']
export const RoomService: typeof import("../app/features/rooms/services/room.service")['default']
export const AboutCard: typeof import("../app/features/settings/components/AboutCard.vue")['default']
export const BusinessHoursCard: typeof import("../app/features/settings/components/BusinessHoursCard.vue")['default']
export const ChangePasswordModal: typeof import("../app/features/settings/components/ChangePasswordModal.vue")['default']
export const CompanyInfoCard: typeof import("../app/features/settings/components/CompanyInfoCard.vue")['default']
export const EditBusinessHoursModal: typeof import("../app/features/settings/components/EditBusinessHoursModal.vue")['default']
export const EditCompanyInfoModal: typeof import("../app/features/settings/components/EditCompanyInfoModal.vue")['default']
export const PasswordCard: typeof import("../app/features/settings/components/PasswordCard.vue")['default']
export const EntrepriseService: typeof import("../app/features/settings/services/entreprise.service")['default']
export const ReservationSettingService: typeof import("../app/features/settings/services/reservation-setting.service")['default']
export const CloseTicketModal: typeof import("../app/features/tickets/components/CloseTicketModal.vue")['default']
export const CreateTicketModal: typeof import("../app/features/tickets/components/CreateTicketModal.vue")['default']
export const RecentTicketsWidget: typeof import("../app/features/tickets/components/RecentTicketsWidget.vue")['default']
export const TicketStatsCards: typeof import("../app/features/tickets/components/TicketStatsCards.vue")['default']
export const TicketStatusBadge: typeof import("../app/features/tickets/components/TicketStatusBadge.vue")['default']
export const TicketsTable: typeof import("../app/features/tickets/components/TicketsTable.vue")['default']
export const TicketService: typeof import("../app/features/tickets/services/ticket.service")['default']
export const CreateUserModal: typeof import("../app/features/users/components/CreateUserModal.vue")['default']
export const RoleBadge: typeof import("../app/features/users/components/RoleBadge.vue")['default']
export const UserStatusBadge: typeof import("../app/features/users/components/UserStatusBadge.vue")['default']
export const UsersFilters: typeof import("../app/features/users/components/UsersFilters.vue")['default']
export const UsersHeader: typeof import("../app/features/users/components/UsersHeader.vue")['default']
export const UsersStats: typeof import("../app/features/users/components/UsersStats.vue")['default']
export const UsersTable: typeof import("../app/features/users/components/UsersTable.vue")['default']
export const UserService: typeof import("../app/features/users/services/user.service")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyActionsMenu: LazyComponent<typeof import("../app/components/ActionsMenu.vue")['default']>
export const LazyConfirmDialog: LazyComponent<typeof import("../app/components/ConfirmDialog.vue")['default']>
export const LazyExportMenu: LazyComponent<typeof import("../app/components/ExportMenu.vue")['default']>
export const LazySkeleton: LazyComponent<typeof import("../app/components/Skeleton.vue")['default']>
export const LazySkeletonStatCard: LazyComponent<typeof import("../app/components/SkeletonStatCard.vue")['default']>
export const LazySkeletonTable: LazyComponent<typeof import("../app/components/SkeletonTable.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/layout/AppHeader.vue")['default']>
export const LazyAppSidebar: LazyComponent<typeof import("../app/components/layout/AppSidebar.vue")['default']>
export const LazyNotificationDropdown: LazyComponent<typeof import("../app/components/layout/NotificationDropdown.vue")['default']>
export const LazyThemeToggle: LazyComponent<typeof import("../app/components/layout/ThemeToggle.vue")['default']>
export const LazyAppBootLoader: LazyComponent<typeof import("../app/components/ui/AppBootLoader.vue")['default']>
export const LazyLogo: LazyComponent<typeof import("../app/components/ui/Logo.vue")['default']>
export const LazyPageLoader: LazyComponent<typeof import("../app/components/ui/PageLoader.vue")['default']>
export const LazyToastContainer: LazyComponent<typeof import("../app/components/ui/ToastContainer.vue")['default']>
export const LazyActivityLogFilters: LazyComponent<typeof import("../app/features/activity-logs/components/ActivityLogFilters.vue")['default']>
export const LazyActivityLogTable: LazyComponent<typeof import("../app/features/activity-logs/components/ActivityLogTable.vue")['default']>
export const LazyActivityLogTabs: LazyComponent<typeof import("../app/features/activity-logs/components/ActivityLogTabs.vue")['default']>
export const LazyActivityLogService: LazyComponent<typeof import("../app/features/activity-logs/services/activity-log.service")['default']>
export const LazyType: LazyComponent<typeof import("../app/features/activity-logs/type")['default']>
export const LazyAccountDisabledNotice: LazyComponent<typeof import("../app/features/auth/components/AccountDisabledNotice.vue")['default']>
export const LazyCreateCompanyForm: LazyComponent<typeof import("../app/features/auth/components/CreateCompanyForm.vue")['default']>
export const LazyCreateSuperAdminForm: LazyComponent<typeof import("../app/features/auth/components/CreateSuperAdminForm.vue")['default']>
export const LazyEditProfileModal: LazyComponent<typeof import("../app/features/auth/components/EditProfileModal.vue")['default']>
export const LazyForgotPasswordForm: LazyComponent<typeof import("../app/features/auth/components/ForgotPasswordForm.vue")['default']>
export const LazyLoginForm: LazyComponent<typeof import("../app/features/auth/components/LoginForm.vue")['default']>
export const LazyReservationSettingsForm: LazyComponent<typeof import("../app/features/auth/components/ReservationSettingsForm.vue")['default']>
export const LazyResetPasswordForm: LazyComponent<typeof import("../app/features/auth/components/ResetPasswordForm.vue")['default']>
export const LazySetPasswordForm: LazyComponent<typeof import("../app/features/auth/components/SetPasswordForm.vue")['default']>
export const LazyAuthService: LazyComponent<typeof import("../app/features/auth/services/auth.service")['default']>
export const LazyAvailabilityGrid: LazyComponent<typeof import("../app/features/availability/components/AvailabilityGrid.vue")['default']>
export const LazyAvailabilityHeader: LazyComponent<typeof import("../app/features/availability/components/AvailabilityHeader.vue")['default']>
export const LazyAvailabilityLegend: LazyComponent<typeof import("../app/features/availability/components/AvailabilityLegend.vue")['default']>
export const LazyAvailabilityNav: LazyComponent<typeof import("../app/features/availability/components/AvailabilityNav.vue")['default']>
export const LazyAvailabilitySearch: LazyComponent<typeof import("../app/features/availability/components/AvailabilitySearch.vue")['default']>
export const LazyAvailabilityStats: LazyComponent<typeof import("../app/features/availability/components/AvailabilityStats.vue")['default']>
export const LazyEquipmentAvailabilityGrid: LazyComponent<typeof import("../app/features/availability/components/EquipmentAvailabilityGrid.vue")['default']>
export const LazyScheduleGrid: LazyComponent<typeof import("../app/features/availability/components/ScheduleGrid.vue")['default']>
export const LazyWeekDayStrip: LazyComponent<typeof import("../app/features/availability/components/WeekDayStrip.vue")['default']>
export const LazyScheduleBuffer: LazyComponent<typeof import("../app/features/availability/scheduleBuffer")['default']>
export const LazyTypes: LazyComponent<typeof import("../app/features/availability/types")['default']>
export const LazyCalendarWidget: LazyComponent<typeof import("../app/features/dashboard/components/CalendarWidget.vue")['default']>
export const LazyDashboardHeader: LazyComponent<typeof import("../app/features/dashboard/components/DashboardHeader.vue")['default']>
export const LazyDashboardReservationStatusBadge: LazyComponent<typeof import("../app/features/dashboard/components/DashboardReservationStatusBadge.vue")['default']>
export const LazyMiniCalendar: LazyComponent<typeof import("../app/features/dashboard/components/MiniCalendar.vue")['default']>
export const LazyRecentActivity: LazyComponent<typeof import("../app/features/dashboard/components/RecentActivity.vue")['default']>
export const LazyRoomOccupancy: LazyComponent<typeof import("../app/features/dashboard/components/RoomOccupancy.vue")['default']>
export const LazyStatCard: LazyComponent<typeof import("../app/features/dashboard/components/StatCard.vue")['default']>
export const LazyStatsGrid: LazyComponent<typeof import("../app/features/dashboard/components/StatsGrid.vue")['default']>
export const LazyTodoWidget: LazyComponent<typeof import("../app/features/dashboard/components/TodoWidget.vue")['default']>
export const LazyUpcomingReservations: LazyComponent<typeof import("../app/features/dashboard/components/UpcomingReservations.vue")['default']>
export const LazyDashboardService: LazyComponent<typeof import("../app/features/dashboard/services/dashboard.service")['default']>
export const LazyCategoryDetailsModal: LazyComponent<typeof import("../app/features/equipment-categories/components/CategoryDetailsModal.vue")['default']>
export const LazyCreateEquipmentCategoryModal: LazyComponent<typeof import("../app/features/equipment-categories/components/CreateEquipmentCategoryModal.vue")['default']>
export const LazyEquipmentCategoriesHeader: LazyComponent<typeof import("../app/features/equipment-categories/components/EquipmentCategoriesHeader.vue")['default']>
export const LazyEquipmentCategoriesSearch: LazyComponent<typeof import("../app/features/equipment-categories/components/EquipmentCategoriesSearch.vue")['default']>
export const LazyEquipmentCategoriesStats: LazyComponent<typeof import("../app/features/equipment-categories/components/EquipmentCategoriesStats.vue")['default']>
export const LazyEquipmentCategoriesTable: LazyComponent<typeof import("../app/features/equipment-categories/components/EquipmentCategoriesTable.vue")['default']>
export const LazyEquipmentCategoryService: LazyComponent<typeof import("../app/features/equipment-categories/services/equipment-category.service")['default']>
export const LazyCreateEquipmentModal: LazyComponent<typeof import("../app/features/equipments/components/CreateEquipmentModal.vue")['default']>
export const LazyEquipmentStateBadge: LazyComponent<typeof import("../app/features/equipments/components/EquipmentStateBadge.vue")['default']>
export const LazyEquipmentsFilters: LazyComponent<typeof import("../app/features/equipments/components/EquipmentsFilters.vue")['default']>
export const LazyEquipmentsHeader: LazyComponent<typeof import("../app/features/equipments/components/EquipmentsHeader.vue")['default']>
export const LazyEquipmentsStats: LazyComponent<typeof import("../app/features/equipments/components/EquipmentsStats.vue")['default']>
export const LazyEquipmentsTable: LazyComponent<typeof import("../app/features/equipments/components/EquipmentsTable.vue")['default']>
export const LazyUpdateEquipmentStatusModal: LazyComponent<typeof import("../app/features/equipments/components/UpdateEquipmentStatusModal.vue")['default']>
export const LazyUsageTypeBadge: LazyComponent<typeof import("../app/features/equipments/components/UsageTypeBadge.vue")['default']>
export const LazyEquipmentService: LazyComponent<typeof import("../app/features/equipments/services/equipment.service")['default']>
export const LazyMarketingCallToAction: LazyComponent<typeof import("../app/features/marketing/components/MarketingCallToAction.vue")['default']>
export const LazyMarketingDashboardPreview: LazyComponent<typeof import("../app/features/marketing/components/MarketingDashboardPreview.vue")['default']>
export const LazyMarketingFeatureCard: LazyComponent<typeof import("../app/features/marketing/components/MarketingFeatureCard.vue")['default']>
export const LazyMarketingFeaturesGrid: LazyComponent<typeof import("../app/features/marketing/components/MarketingFeaturesGrid.vue")['default']>
export const LazyMarketingFooter: LazyComponent<typeof import("../app/features/marketing/components/MarketingFooter.vue")['default']>
export const LazyMarketingHeroSection: LazyComponent<typeof import("../app/features/marketing/components/MarketingHeroSection.vue")['default']>
export const LazyMarketingNavbar: LazyComponent<typeof import("../app/features/marketing/components/MarketingNavbar.vue")['default']>
export const LazyMarketingOnboardingStep: LazyComponent<typeof import("../app/features/marketing/components/MarketingOnboardingStep.vue")['default']>
export const LazyMarketingOnboardingSteps: LazyComponent<typeof import("../app/features/marketing/components/MarketingOnboardingSteps.vue")['default']>
export const LazyNotificationService: LazyComponent<typeof import("../app/features/notifications/services/notification.service")['default']>
export const LazyCompanyService: LazyComponent<typeof import("../app/features/onboarding/services/company.service")['default']>
export const LazyCreateReservationModal: LazyComponent<typeof import("../app/features/reservations/components/CreateReservationModal.vue")['default']>
export const LazyDailySummary: LazyComponent<typeof import("../app/features/reservations/components/DailySummary.vue")['default']>
export const LazyReservationDetailsModal: LazyComponent<typeof import("../app/features/reservations/components/ReservationDetailsModal.vue")['default']>
export const LazyReservationStatusBadge: LazyComponent<typeof import("../app/features/reservations/components/ReservationStatusBadge.vue")['default']>
export const LazyReservationsFilters: LazyComponent<typeof import("../app/features/reservations/components/ReservationsFilters.vue")['default']>
export const LazyReservationsHeader: LazyComponent<typeof import("../app/features/reservations/components/ReservationsHeader.vue")['default']>
export const LazyReservationsTable: LazyComponent<typeof import("../app/features/reservations/components/ReservationsTable.vue")['default']>
export const LazySelectEquipmentPanel: LazyComponent<typeof import("../app/features/reservations/components/SelectEquipmentPanel.vue")['default']>
export const LazyWeekStrip: LazyComponent<typeof import("../app/features/reservations/components/WeekStrip.vue")['default']>
export const LazyReservationsService: LazyComponent<typeof import("../app/features/reservations/services/reservations.service")['default']>
export const LazyCreateRoomModal: LazyComponent<typeof import("../app/features/rooms/components/CreateRoomModal.vue")['default']>
export const LazyRoomStatusBadge: LazyComponent<typeof import("../app/features/rooms/components/RoomStatusBadge.vue")['default']>
export const LazyRoomTypeBadge: LazyComponent<typeof import("../app/features/rooms/components/RoomTypeBadge.vue")['default']>
export const LazyRoomsFilters: LazyComponent<typeof import("../app/features/rooms/components/RoomsFilters.vue")['default']>
export const LazyRoomsHeader: LazyComponent<typeof import("../app/features/rooms/components/RoomsHeader.vue")['default']>
export const LazyRoomsStats: LazyComponent<typeof import("../app/features/rooms/components/RoomsStats.vue")['default']>
export const LazyRoomsTable: LazyComponent<typeof import("../app/features/rooms/components/RoomsTable.vue")['default']>
export const LazyRoomService: LazyComponent<typeof import("../app/features/rooms/services/room.service")['default']>
export const LazyAboutCard: LazyComponent<typeof import("../app/features/settings/components/AboutCard.vue")['default']>
export const LazyBusinessHoursCard: LazyComponent<typeof import("../app/features/settings/components/BusinessHoursCard.vue")['default']>
export const LazyChangePasswordModal: LazyComponent<typeof import("../app/features/settings/components/ChangePasswordModal.vue")['default']>
export const LazyCompanyInfoCard: LazyComponent<typeof import("../app/features/settings/components/CompanyInfoCard.vue")['default']>
export const LazyEditBusinessHoursModal: LazyComponent<typeof import("../app/features/settings/components/EditBusinessHoursModal.vue")['default']>
export const LazyEditCompanyInfoModal: LazyComponent<typeof import("../app/features/settings/components/EditCompanyInfoModal.vue")['default']>
export const LazyPasswordCard: LazyComponent<typeof import("../app/features/settings/components/PasswordCard.vue")['default']>
export const LazyEntrepriseService: LazyComponent<typeof import("../app/features/settings/services/entreprise.service")['default']>
export const LazyReservationSettingService: LazyComponent<typeof import("../app/features/settings/services/reservation-setting.service")['default']>
export const LazyCloseTicketModal: LazyComponent<typeof import("../app/features/tickets/components/CloseTicketModal.vue")['default']>
export const LazyCreateTicketModal: LazyComponent<typeof import("../app/features/tickets/components/CreateTicketModal.vue")['default']>
export const LazyRecentTicketsWidget: LazyComponent<typeof import("../app/features/tickets/components/RecentTicketsWidget.vue")['default']>
export const LazyTicketStatsCards: LazyComponent<typeof import("../app/features/tickets/components/TicketStatsCards.vue")['default']>
export const LazyTicketStatusBadge: LazyComponent<typeof import("../app/features/tickets/components/TicketStatusBadge.vue")['default']>
export const LazyTicketsTable: LazyComponent<typeof import("../app/features/tickets/components/TicketsTable.vue")['default']>
export const LazyTicketService: LazyComponent<typeof import("../app/features/tickets/services/ticket.service")['default']>
export const LazyCreateUserModal: LazyComponent<typeof import("../app/features/users/components/CreateUserModal.vue")['default']>
export const LazyRoleBadge: LazyComponent<typeof import("../app/features/users/components/RoleBadge.vue")['default']>
export const LazyUserStatusBadge: LazyComponent<typeof import("../app/features/users/components/UserStatusBadge.vue")['default']>
export const LazyUsersFilters: LazyComponent<typeof import("../app/features/users/components/UsersFilters.vue")['default']>
export const LazyUsersHeader: LazyComponent<typeof import("../app/features/users/components/UsersHeader.vue")['default']>
export const LazyUsersStats: LazyComponent<typeof import("../app/features/users/components/UsersStats.vue")['default']>
export const LazyUsersTable: LazyComponent<typeof import("../app/features/users/components/UsersTable.vue")['default']>
export const LazyUserService: LazyComponent<typeof import("../app/features/users/services/user.service")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
